name: bible_decision_simulator
description: Daily Turning - Interactive Christian Decision Game.
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  ios: true
  android: false
  image_path_ios: assets/images/app-logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/content/
    - assets/config/
    - assets/images/
    - assets/i18n/en_us.json
    - assets/i18n/vi_vn.json
    - assets/portraits/
    - assets/portraits/male_01/
    - assets/portraits/male_02/
    - assets/portraits/male_03/
    - assets/portraits/female_01/
    - assets/portraits/female_02/
    - assets/portraits/female_03/
